### ISSUE TITLE
Failure to deploy to Glitch.com

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/auto-cancel-actions#77]
The deployment to Glich.com started failing on 1 September with a message like this one:

```
error Fail to sync changes in your GitHub repository to glitch.com
Exiting with error code 1
error Command failed with exit code 1.
```

See https://github.com/renovatebot/auto-cancel-actions/runs/3737689271#step:8:15

**Comment by viceice** [comment]
I think we can archive this repo and fully switch to buildin option

**Comment by HonkingGoose** [comment]
@rarkins What do you think about archiving `renovatebot/auto-cancel-actions` and switching to the builtin option?

**Comment by rarkins** [comment]
Fine by me
